#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
#targetType=libso
#. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

set -x

./src/Allclean

wclean ./applications/utilities/preProcessing/canteraToFPIFoamV301
wclean ./applications/utilities/postProcessing/FPIFoamV301Post
wclean ./applications/solver/FPIFoamV301
wclean ./applications/solver/FPIBuoyantFoam-v3.0.1

# ----------------------------------------------------------------- end-of-file
